module Export
  module Newsweek
    class PurchaseExport
      ACCEPTABLE_COUNTRIES = [
        "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
        "Anguilla", "Antarctica", "Antigua", "Argentina", "Armenia",
        "Aruba", "Australia", "Austria", "Azerbaijan", "Azores",
        "B W Indies", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
        "Belarus", "Belgium", "Belize", "Benin", "Bermuda",
        "Bhutan", "Bolivia", "Bonaire", "Bosnia", "Botswana",
        "British Virgin Isl", "Brazil", "British Guyana", "British West Indies", "Brunei",
        "Brunei Darussalam", "Bulgaria", "Burkina", "Burma", "Burundi",
        "Byleorussia", "Cambodia", "Cameroon", "Canada", "Canary Islands",
        "Cape Verde", "Cayman Islands", "Chad", "Channel Islands", "Chile",
        "China", "Christmas Island", "Colombia", "Congo", "Cook Islands",
        "Costa Rica", "Croatia", "Cuba", "Curacao", "Cyprus",
        "Czech Rep", "Denmark", "Djibouti", "Dominican Rep", "East Germany",
        "East Timor", "Ecuador", "Egypt", "El Salvador", "England",
        "Eq Guinea", "Eritrea", "Estonia", "Ethiopia", "Faeroe Islands",
        "Falkland Islands", "Fiji Islands", "Finland", "Formosa", "France",
        "French Polynesia", "French West Indies", "Gabon", "Gambia", "Georgia",
        "Germany", "Ghana", "Gibraltar", "Granada", "Great Britain",
        "Greece", "Greenland", "Gruzia", "Guadeloupe", "Guam",
        "Guatemala", "Guinea", "Guyana", "Haiti", "Holland",
        "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
        "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man",
        "Isle of Ornkey", "Isle of Wight", "Israel", "Italy", "Ivory Coast",
        "Jamaica", "Japan", "Jerusalem", "Jordan", "Kampuchea",
        "Kazakhstan", "Kenya", "Kiribati", "Korea", "Kuwait",
        "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Leeward Islands",
        "Lesotho", "Liberia", "Libya", "Lichtenstein", "Lithuania",
        "Luxembourg", "Macao", "Macedonia", "Madagascar", "Madeira Islands",
        "Malawi", "Malay Peninsula", "Malaysia", "Maldives", "Mali",
        "Malta", "Marshall Islands", "Martinique", "Mauritius", "Mauritania",
        "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
        "Morocco", "Mozambique", "N Korea", "Nambia", "Namibia",
        "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caladonia",
        "New Guinea", "New Herbdon", "New Zealand", "Nicaragua", "Niger",
        "Nigeria", "Northern Ireland", "Norway", "Oceania", "Okinawa",
        "Oman", "Pakistan", "Palau", "Panama", "Paraguay",
        "Peru", "Philippines", "Pitcaran Island", "Pohnpei", "Poland",
        "Portugal", "Qatar", "Reunion", "Rhodesia", "Romania",
        "Russia", "Rwanda", "S Korea", "Samoa", "San Cruz Island",
        "San Marin", "Sao Tome", "Saudi Arabia", "Scotland", "Seychelles",
        "Sierra Leone", "Senegal", "Singapore", "Slovakia", "Slovenia",
        "Solomon Islands", "Somalia", "South Africa", "South West Africa", "Spain",
        "Sri Lanka", "St. Helen Islands", "St. Pierre-Miquelon", "St. Vincent", "Sudan",
        "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria",
        "Tadjikistan", "Tahiti", "Taiwan", "Tanzania", "Thailand",
        "Togo", "Tongo", "Trinidad&Tobago", "Trinidad", "Trucl Sta",
        "Tunisia", "Turk Caic", "Turk Islands", "Turkey", "Turkmenistan",
        "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
        "Upper Volta", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican",
        "Venezuela", "Vietnam", "Wales", "West Africa", "West Indies",
        "West Sahara", "West Samoa", "Windward Islands", "Yemen", "Yugoslavia",
        "Zaire", "Zambia", "Zambie", "Zimbabwe"
      ]
    end
  end
end
